### ISSUE TITLE
內容長度不足時，Footer會跑上來

### ISSUE THREAD

**Issue by wijinlau** [maibee/maibee#5]
內容長度不足時，Footer會黏著內容跑上來。
Amos說寫個js來固定內容長度如果不夠的話就設定內容高度為viewport的高

**Comment by LinGaryTW** [comment]
我在設定會員登入的時候有把footer定在夜尾了
等分之合起來應該就會解決

**Comment by wijinlau** [comment]
讚

**Comment by wijinlau** [comment]
要把footer置底的方法改用javascript做
